In [12]:
#NumPy (Numerical Python) is a library for handling arrays, matrices, and performing high-performance numerical computations.
# It’s way faster than using plain Python lists for numbers because it’s written in C under the hood.
import numpy as np

In [22]:
# Notice that NumPy defaults to float64 for numbers
# Creates an array filled with zeros, with 3 elements.
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((2, 3))  # 2 rows, 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# Creates an array filled with ones, with 5 elements.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones(5, dtype=int) # if you want integers instead of floats, you can specify the dtype

array([1, 1, 1, 1, 1])

In [29]:
np.ones(5, dtype=int) # if you want integers instead of floats, you can specify the dtype

array([1, 1, 1, 1, 1])

In [36]:
# Creates an array of the given shape, just like np.zeros() or np.ones().
# But here’s the kicker: it does NOT initialize the array values.
# That means the contents are basically whatever happens to already be in memory—so you’ll see random numbers.
# Why use it? Speed. If you’re going to immediately fill the array with real values, np.empty() is faster than zeros or ones because it skips initialization.
np.empty(10)

array([ 0.1 ,  0.2 ,  0.25,  0.5 ,  1.  ,  2.  ,  2.5 ,  5.  , 10.  ,
       20.  ])

In [41]:
np.random.randint(10,size=4) # An array of 4 random integers. from 0 to 9

array([7, 9, 4, 4], dtype=int32)

In [43]:
o.shape = (5,1) # Is a 2D array with 5 rows and 1 column.
o

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [46]:
np.linspace(0,1,10) # np.linspace(start, stop, num) creates num evenly spaced numbers between start and stop (inclusive)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [51]:
np_list = np.array([1,2,3,4,5,6,7,8,9,10])
# Why use np.array instead of a Python list? Because now you can do fast vectorized operations:
np_list * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
first = np.array([2,4,6,8,10])
second = np.array([1,2,3,4,5])
second>3

array([False, False, False,  True,  True])

In [63]:
second<3

array([ True,  True, False, False, False])

In [64]:
second.sum()

np.int64(15)

In [65]:
more_than_three = first[first>3]
more_than_three

array([7, 7, 8, 4, 9], dtype=int32)

In [72]:
first * second

array([ 2,  8, 18, 32, 50])

In [73]:
n = np.random.randint(10,size=5)
m = np.random.randint(10,size=5)
print(n)
print(m)
print(n+m)
print(n*m)
print(m @ n) # The @ operator in NumPy is matrix multiplication / dot product....  sum(m[i] * n[i] for i in range(len(n)))


[5 8 2 7 9]
[2 4 4 8 7]
[ 7 12  6 15 16]
[10 32  8 56 63]
169
